/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Core surfaces & semantic tokens — from Kinetic Indigo Precision design system
        surface: '#f8f9ff',
        'surface-dim': '#c9dbf9',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dde9ff',
        'surface-container-highest': '#d3e3ff',
        'on-surface': '#091c32',
        'on-surface-variant': '#474556',
        'inverse-surface': '#203148',
        'inverse-on-surface': '#ebf1ff',
        outline: '#777588',
        'outline-variant': '#c8c4da',
        'surface-tint': '#5036fa',
        primary: '#3904e7',
        'on-primary': '#ffffff',
        'primary-container': '#533afd',
        'on-primary-container': '#ddd9ff',
        'inverse-primary': '#c5c0ff',
        secondary: '#4d6079',
        'on-secondary': '#ffffff',
        'secondary-container': '#cee1ff',
        'on-secondary-container': '#51647d',
        tertiary: '#3b2cc4',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#544adc',
        'on-tertiary-container': '#ddd9ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e3dfff',
        'primary-fixed-dim': '#c5c0ff',
        'on-primary-fixed': '#130067',
        'on-primary-fixed-variant': '#3600e1',
        'secondary-fixed': '#d3e4ff',
        'secondary-fixed-dim': '#b5c8e5',
        'on-secondary-fixed': '#071c32',
        'on-secondary-fixed-variant': '#364860',
        'tertiary-fixed': '#e3dfff',
        'tertiary-fixed-dim': '#c4c0ff',
        'on-tertiary-fixed': '#110068',
        'on-tertiary-fixed-variant': '#3828c1',
        background: '#f8f9ff',
        'on-background': '#091c32',
        'surface-variant': '#d3e3ff',
        // Raw brand values referenced directly in DESIGN.md prose
        'brand-hover': '#4032c8',
        'brand-border-tint': '#d6d9fc',
        'brand-ink': '#061b31',
        'brand-slate': '#50617a',
        'brand-line': '#e5edf5',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        'display-xl': ['56px', { lineHeight: '64px', letterSpacing: '-0.035em', fontWeight: '700' }],
        'display-xl-mobile': ['38px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-lg-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.005em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        margin: '2rem',
        'margin-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      boxShadow: {
        level1: '0 2px 4px rgba(50, 50, 93, 0.04), 0 1px 2px rgba(0, 0, 0, 0.02)',
        level2: '0 12px 28px rgba(50, 50, 93, 0.08), 0 4px 10px rgba(0, 0, 0, 0.03)',
        level3: '0 24px 48px -12px rgba(6, 27, 49, 0.18), 0 12px 24px -8px rgba(50, 50, 93, 0.08)',
      },
    },
  },
  plugins: [],
};
